language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_MageTrashApp
  - secure: SpgjWxV1uhOPM9121TVtcYzf5FeZDDkC1qboZpjIm/fyQ4DiQQTruJ2C/wPO/tcE7FEzJRW2ubkignGzGkRYRgsWUHZXcafm/CTMeRbokNTTw8ArnmmUwJ7OQkEPkIdyFFi0HwgMI4pfvqbz0TjJkp21CmfQed+98PO+Mk50GI6etI3J7PdXwVdRF1G1+GjGhfH3MQjPYLLWNExgYGVkNgPCdO400lZf6v5HFUXEw7h9JHMkrSJ1Vvp13HgwXntHbVEDrgL94xHoVR8pxv+Y0XYMPe33iQaWRGUfsBs3qeorivpQ6M5ipvb/P2e5DCVboB+jLGL2up39PyRu0zxx5nOgZGb995qhI7tK/gdnz1NQLcYcRFyAwnW8EkHsM7cU0WS2z+oFCn89stltfiouEp5urV962p2DtqbL4wHRQyMItQ1OOR3D/uxtWTVIM1XbOzeW8V6yIiwqYrA2cPupMER3z0A939xfUK+ik9q3cUxpEYL3LNcjJPfEmUx51+0Vf6Xqz/hq6Oct8ATPix5Ag5l7CaQ/O2xkph5VNM3X6MUb3gnA3kIJUKQ9r5jZOGRK0EntoHo0G08Yx+8XAiMC8u75EcUL5HNRK7XtgQUzTyS4g4I/RqbK1PRpT/b6dhRXtN0LnXUzzcD7xiQ10dL3Ir6shMfGdMyJmqfQpqnkl9U=
  - secure: RjjrtfoZbewVTZFqumj+s7zvVRaxGlm1/jUehK7Dn9iT/9k1YhCjUesN34a60VwhuvSvqSvpsSO785ft5+OCndLj9aYTb7SMpkyT2o2n/tDOEvjIp16hqUdhdI6e7wkd+Bm3AoTx80z2/FDgUbGTWpxeNnIjaf4sQHVYDNoQJ1JJpEbLG5D1JEuzD66ofUluojmrjzUi5L8JvT84HWvwR7/hWoRLW3AzkwI6sKZEMrQO9oQfrO42H27uSNqoaHzqeUQ/0fq7euC1hX6ut064wWPgOolfsSU8MGgiXZUTJP6Iv2vdN1TVVskk7RHKC53wnZCX0goP+mjKMVZhvSTzEEzmtoz0ycJJBWejgW0nbPEXOdBYIqmTOWQfshIBibrn8p5uy6zMifl3ZAmPAjSuewOkHz317DfWnXwY4XWfgJ0jkKJnifHXcM8uEXrdEhpnIhG40yD5AGEv2m9aA9qJChvYDHlHvFgYYb8Ti5UC6TsmapEKfE+8ZrwMaRe6zZJOLNFnXWICAHzCVLFLAl7dsy5cCNxP119pFQiHzSekR1+M96U3vnoFXeVQ0HshQgcoNk3N/z5NcSwYykO7OM+vlzYVzmxujEXYrrftPBS4QAOjhDu1e06D6BiX1dHOa9Lrl/1cVp7AJPGqMTkUFW0TO8JkRrmA+X3jyrzV4GgcFhY=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: N7UZfp4ctpzvp2vTf69c+On24i0dUbft2Txk1qWcXCr3o+BXRnTED48d+0IrONxTVfOwaYL2CoW62fyH7D+4m0MpZVatgmBP+t04hV83v5rLVXwSo2mTygK1kJclK8hjTtE7PX5f5n+mWHRnaCmj3+o6v/nKe9JTbiSyE2pu9DeN7QdkCAE55bN/NTkj2RPfS+41l9/IDfXqUm89j81QC37EK20VA7vKMjkE/n6JZeIe4sTxl9CIYdsaPrjKgqqjgviay0TQEfVT1QFMor3khWOhAO1uj+bptPPksowd+dWg0v+v8OeIshK4/+ZmN+XOhHkH4Z12WM2aUdoaj4woH1Td34K15LDkwZs5ecOrbavuVYBg4w0YKPuOMf5SAeNf9NSw9P+ysrpqI7M5G75xfSvlKxhIBOn7FiQsfrPFWzKjBt7Rab0Mi68mMTIseQiOuSNRKKAO2jrJVpfsiXRVtwK3KptjTORbQU0AMF9KR5CFWkSVmxT4Donw8Gpipud22oftARoqrSfOGznQ1furBhDjHc9B5PitOIIRK7rkuWNRo7p9K16TinJ2IFZAO4DIugvHxFfeXO1fqKKFmDLknxEVJL1FO9YzH8VuyKyPUqmu91yHtP9XlQjCSxVT0j/1Hf+yXR+3uYSbpBdxosIzYy/4RxhWhtzIYuqgXQimVrE=
notifications:
  slack:
    secure: OEdyLvAjtMQc8qOqN7pRm+9BNK0vG0iwuyxrHDwmQsuTazFJDeZ/TclVjVBqkrV1NFPkflt+6dHnfp7V1Jk9vmAl8cMX7GFq6ZFsH39Sy0HPI5jBVdzgogqF8DNTwee5lztaUAhUWBqsdBTpccV0u1fDkF0yCt81A3SM/JMC79jvyQ7fkYj5mzqAClFfM/KwnNoFL5j+WlmSAmgOC6SL39w7/6ajaEKOb0OJ/c25LUgOGDCSgsiSxPWCNYit4ov7sJde7ouXkpXXV8J8or1vYaJy1XhIcNdeUy33b/IDqJxqBFidpC3B6u/l9pogATNqeYrB9vJsQk9ivmfVd3l6FWhS+pIr4jws7lI+xLLrIH+zyYavNYVJXoON7M3p7DrAJOSmLuUwIum+g0c13j88fW7pr0J1NzeIZIQxhzrAUSqCLqnffcEbg7s08s8/rbyjRn9sGblXjdLnpY28gb6ZWxMW4W5j3kfbmtYq5wllaF39OSDf44Nyhz8/Evjd6FNoHF8o+wx90tzHAz+hl55TpM0cV2e3bW/z53BA2FRxX2SMGc6pzFJbae+ZLWk+ECf6ErCAVmg7qOVXcc5Z+XYgXb4GwnVTED5MpOj4uYjlBFLbCtXCtWXnVKQRTcLKGY+JzevkyI3uvCCyseHM8/7hzrY8Y3ag1f0+Q09H9opWadc=
