language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.4
  - php: 5.6
  - php: 7.0
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.0
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
  global:
  - secure: mvyPXYwvpvzMG46/twCWOg+ifefd8Gl1upEEvkrs+hvohU3gYNqi8+QYCbr3BN51QInBKR9yXnzNbszCFeFOobuhiidjPYj0etrVqZuU5cOckoadVy5FKV6VYtM8CnW0shgbyuGwRrP8u8kHofRI0jrjs7haYCWYxIU6Jt1vbyp/Y7h3hVVTkmvwx3BpjmiX7d9M08HfrLZilROD8gAkGTCpY+WD8Nnzr0oo+fA/pj5waQ1VB5iLhpY9Pk8+/LcEOX1n0TtTGSr+Z6vsCaCY0p4cD3nwlkuFcEJBAmWGFMf2ugU+tgMBQS0kxL6QeOafD6t8hv8A6kv1Rwt37q5V7FHCyZ5mPzARThSdXukqleNy8T8UU6g9IJac86ziEOaoa3VxBmD33fgn4Ig4lGK3cmjFiLJHCG8k7/zlMyvUR5ox9I8TfMiG2ESEoXj4yVfHqPG58Zit7uMHnnJDSQRRfxDKiEnS/rJFxmDtrbwe96wkIW/MFvOMgYETx+47Tub13Mq34pGegbLOlqEuAgggJFdlpgaIb587PMpchb/n6nLpJq8bNnyHnLTWTwpNwtwgx22VyMj5Hk4Mxzc+7xFWEH34l4qGcLe+JsWwAHmEQ2ZoH4gjebeomukPSh+CfiavYg7WvWFRqoAVF3965BEL7wk84uXJOKwnpB4V5prmdn8=
  - secure: ch8NP5tBYQR2pUIRpOHgwjt6jYgM3geHrsiNys5Lp60JIJvRYVIdkDSBJH3n7VAhXouZIHEmrZIhlWK9dy6hZ5JydSnGnaAYTPQwcNJLPZ0cDzE2NjrdWdwKQidxzz9O/YK95L+IS08apGcCrK+k353LaeqhzX0PouIpkEqwSvboLjtCl+L4KqnVLplKb2/6zChtdWydLKQdqNCZxBQk/NI/TDOHXZSOIJMnIHaDqI4SMrpzRTORp3sR2c7dSS7GYllaxFjzWUWS2ayx3IhsndDg9NWFrGld7S9vfzZKmMVgb29ATSBiag1gQZ0KCMzxpUgcip98S59c9ATLMiMEFA13qM2v8+8MLbMZ0US9DhXyFl1x2/gp9TlAZ/oHHvCK5VvpWqUCdXdEKN+MFKnjkN+8B9zTGoZca9eXXCzbrCTN0Sb4chk6N7OxHNofvRRU/W+0f38XT/KUNU7i9+klvmP09KteZh1LvshrR+xC6vy9famhtpDSJqK/pcJe83RGJKawtjfig9kWKBNRWVq9Pe/6Cm2g6qgWwqySE6k30I2C/7KQuU0Bm32+TKIjOySKzbI2h6ps383lVvuZeFZG/0KopfhB48zit3kNx1oY/itLN9DtOyqtKTEizN8HQNeoacpHK1pjLZwUuKiL4XCwDxM8aeVapgl7YiAfsvv5ei8=
  - secure: PO2VAYr/OTj1gdHw1Tcg+1v5LRD0eu+555yGeAyQdjhfaCGrnxsuRghd6MU43Gw6bc64wEU5nSzkJW1s3Np9UmmgOjBXCkRkrZ5qamSh9hiXEMdlFI9dHFZh9sB4l9+9WeRd9cUtgv1gCN84wueciOPaP01wS63fqUn7AmJGb+1vYXOyoqaqg3CJXS5ZfxtwKvm4uqueSczkHrUWSLrOhWvMcAiOD5zRRop1M2gNqCt36TQCNHF9m1f88O1QxItvuCFG7JupFzr/NhmiWAFvsfIjhse4UJIiVvUqdb+KchDPP/uBScLeKP9NnyV6c4PcXdj7fzEpfB1Q5ekXol3rAuIUUtfGtmj9Mmm1sWSNkDCG5J2WBRsW6CSMhFNVLogwCk9OIgPrsPkr/pX7o/4hELFhooemWMDQhC2jbEJBidfdMk8BsnZezgaVQMNSFOP/DgKdyTDO2AqZBVza4JsxvH44mpSdnlzav4VL9hhC+M+iPMGvOcDs6SjKBaPR/ccyZnT8MGHxFMfVPVLehKEK7VM5XTDahKwPfV2p/5xEDr7RSOfGyLAMJKm6VZ6T/aID5N7ENNCP+rnHpuOG8y3ERCDd5E6N4INuSElaKitZ5r/0ziMCeA6TZuJ1if35uQ4gxPVWlGDq5xByM0z/IJvowInk8lIUVV/qjN1mHppSY+s=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
notifications:
  slack:
    secure: TXRr9j/1w4JCygbvOpVIlNDSg9vicYDuzTZeaVjtbpLduNtTuzu/kjAXVotL7Yst0+9Wr7EP5MPE6qHYRMjeolicUQoyfGQswGM3mFKTrWcZrQmRHILog6S6wl3Z+2mYXhee0bVzvnoABuC5I3dxd4+cWU2rpzH5lUeco9zTFTXEVy8vCeIeFQ+BF8rAXh38tmVAG/Nyas176x3pMnLOjGpdqaqlN4jHa+ya18XP7YBOqnFfhMXP4W09k9rCUVdIU4S0DpKZEyrJZJNtWyHHYnJpFZDtUuoQ3HdQeWZs7OIYeIj9Dom7qNC6O4exFCcsByADGeu701OmM3CvEoGy+d8taSK/BajW9KLKyLH2zb/H6Hc24uPMydrU5pkq4bLic/dYGw71wtP+3GFwoDFUhMyUp+60vvVC96boSPIn4GwZ/x7vhLgybZIQ5xCsZNSRH2IMRYyDzh+5y1d4750b2u+uGGupbLLmQpZbno97zL9J0bESZ+YWPxhhUP9gF1TYnnGp7KvtJB/n9AAy1SNMk5w6cpPPhRsWx5E9DBbmroTYUnB4o815EQFVidV5QYc+anV6+UT1JsOYdjxfqCqyJ4TBVfRu118vE7BhmmIDudFtnn5vRYPyGHFwBMWwqzrG9BUuk2knyajq4UhD0SK7HES8TPDvQjSxCQNRh457lT8=
