language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  allow_failures:
  - env: MAGENTO_VERSION=magento-ce-1.9.1.1
  - env: MAGENTO_VERSION=magento-ce-1.9.1.0
  - php: 5.3
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.2
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.1
  - php: 5.4
    env: MAGENTO_VERSION=magento-ce-1.9.2.0
  - php: 5.6
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
  fast_finish: true
env:
  global:
  - APPNAME=Ffuenf_MageTrashApp
  - secure: jI/IxViZ/pJGg5mZMq4FD+b336Bu4vL/O3E+490UeqjgFT2U3RqHMwqr88ZJqar+B+jS4ycCsbSi++SiMx+D32nlWrExA+Vw/mut62UelYR1ixrcKGdJnclNaN/PHVLqDCoSCzVbjIH/WSR35KO88aeIjMO2vj2wesYkW0xCT6X6weBcLyuchHvjN/G9jDi6hfqRgCvZW+fuBGezMYLXhRF0zRUZwIFoUky1sTpCuJmErraalJc2McMc9GWNl41llfCqkgkUUvSV7yWsYAV7EtaLjpkrOU6XuJ4DvVWB7K/rtZKoXP+VCBu689POVe88LmnnmqsGUAWBtpS8ZnjAGjKjuIVesvVRhqxyScqOD/UgrxPZSm8YnjiyNXtTq+hu+c3lKZ7ygcTNiIiPlc2ULecREdk2IuFW4ZnJqOezKBAvVTS9LMsw2sksvZx2SifQJm4nRl3oYKovbEbBoC2q6xkrP0kZPlfDdROHyK7G+5cXhaGqRySHUJDWQbinYDFZinx6yfEZ/UguVlktinEq18faHpmpFdBV7F8/3+cIr6bdS2LZaIj4hI8Oaxr6a8nCebO/ksf0hI0cVyzI8tMYDSDMVMEsHaLrmytUeVbDrG7iL4pQpdyw1dugQQNexRHBp76qZAjIvBWD67rfSBjcMFh4QglgtU/YrgUJs3S6dHE=
  - secure: cWUKXufGNKSfZJqi/YM4UJA8Hfy2fFCrUsyW096X1gVIOZneBjo/YfA/dnWs+rLFbESyea793CjxpYuyCYlswXt2WTbxg4DDrxGXFfeZf6oqEM5D/uCqN/1bn9VZEWfzdGjY6m6t6buFoivoHHvWn5+jsSxqTKKZ+bEIQH0N5c7KvrCK9HzW7cg/f63BryvppGptoWxC1PQzSK1f8CwYE8sNff28crg8lK7r4AvhS0CMNf2bkV2Aiq82caXahp87h7QreTVYWfDOZ/S7oBBeZY3VfjCybAvgmzTPr5beOINZpfn8EGJE/+SEUNIkh8hNuDTARUnyD/4rz/1GmG4CPaVTIYABzpZUsUnuk4e2NrLhOqDdjyCleuFzaNFzJOCk2Vm8fKTXQASSasSHlnlH0nnfojqsHfB/u8C9iP370tRSpMS0bALY1bzinbRlzPyi/hYoQduebd4aT1ZQ0zJkCpQjNFeDrttVAcQJ2SS/t7fn3gKlLmGN1IvoWcpQ37/8XgYuw2jHIwvFUSwv+WR0lZFU4cAqqfjhubFlpm1E49jOWJixKgBlTldRsrcOFJ3pQ7xq455+Z0kDHF8FpzwDUgjQeiYw0BcGAg048XhrjF1EncWgOimw+ZT8/e8Lh+Ueb5vc3QXTOJkIOipwgnMCcGkKvKAQHNVfDyAk28+oXu8=
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.0
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-ce-1.9.1.0
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
before_script:
- composer self-update
- composer install --prefer-source
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: V0Z2CA1lei5tALpxVEemrG1WW5iPmKyvkQ7eVeeDLwr5oRcDcOPx6MQy8/isrQ6qZA9fAFq41cfk4lY4osBpqKi6mExTGgTTexRofmR/83WbtKOl7EEcSYheRT2hDaSlhv2oeFStvbYTkHGFvwSI8i5vvZj95dl91i/BDxzgwMduPVoW/c0+DGqlSfihI16PN3zNC6d2vacBmef5ahbMFZXNXdChjgdXq+IRrI/jkk31ta6cuRVOU1wWYxDp19vDXozYS2qTwPg3YCGrzZZUUA8WqAv8PT9XIfp7CM+a5LEOaOCv4Gf6uv94cqwdh7I2Oi9xepWXBjn9GTJlyzkNLFb3yPXaqV2tiy+QzfRBE2VSuFfX+3iYOPd9SKbz5bA3uJmHaGv3EXY+4Bluqqv2NflMGQnwquYkZ0ZY1u+vFd9SHHxW8RpOHKpv2S2W+Hbjlxmigopzd0moNyMuaOVnKm7NpsbniInHejHfETDnwnk8IIWXjKTbrjAGXKWM1JwzkbxoR0pp8TsUUYbWZ0KIIXvPSsfhvz6fhXF+uiEIarittr09kx1GeGBK0ZrL5bGENQ+iRILBI4WisxUp685RcBtETKx/QB0sfiJ7fGbDRn2Y0d19wO8ZcCBk6N9oj62b1FaapRVQEpSdrkexXT1uOJlfvvRYFAR0BVP3PrR/Ihg=
notifications:
  slack:
    secure: RqS6QkZrU541+aYwRj6KQblc5U/zwZ3fVypKmiXG85olTpZIyiWVg8k70lHqnwroAIdjrNZWWWLMeNzgtoI+nR4ORVvW1wrB19mNxtsoIaDvG/JJa4JppBrOIeDDmZxfIB2MK7F+dzFd8GrViuJymLh5ifN2f81WsO4vNeMUIvg/832ahfgWE+ZBJmiBQ8a79HhVScLOhdGExGIF3SozZ6tIrX+QP8uv6BM6DPdm28sW2/KWtD1pRoZ3A/MD+p3n4MOCFModIF81HwRxG0MNvfxp5rQzkVXLlDLkXQ+T8I6rGkgTu/qMvd2e1NJnwDqjnxIGkrmseV8cMg0rqmog5GKRCUMzISBDZGiokQqCT+UGYl1tkLCRIwcJHg94sOLu2HPJ/CCmIu2dNsvF/CS0sfQEAb9xd50FgX/Nj7k1PYRKNNxe5FsE8qCieVTrRR5U+fYrq46y877k3C/UVwLAZeFbpeJcAjoPb1A2bNVDxdA6oTyXuX9F7jBVzE6MLPU4RcINhpCNA/SSsxJLfFz5GnxHqSaOFaSOUdpNJfd/J1XvTu11/g98Xt1NWJ+r4AOOBOY3z8rRmyT2migTJVagVkmd3ZfqPqhdNlio2i903F/eGr45hogRzTJmw0Vd34mjRgX+xK03vb8+lkRLPMoyFEZpr7wpQcVpbcsURchUVUU=
